name: check_for_new_version

on:
  workflow_dispatch:  # allows for triggering workflow manually.
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check-version:
    runs-on:
      - gha-runner-scale-set-arm64
    env:
      REPO: grafana/grafana
      TAG_REGEX: '^[0-9]+\.[0-9]+\.[0-9]+$'
      PAGE: 1
      LATEST_TAG: ""
    steps:
      - name: Install jq
        run: |
          sudo apt-get install jq -y
      - name: Fetch latest semver tag from Docker Hub
        id: fetch
        run: |
          fetch_tags() {
            curl -s "https://registry.hub.docker.com/v2/repositories/$REPO/tags?page_size=100&page=$1"
          }

          while : ; do
            TAGS=$(fetch_tags "$PAGE")

            MATCHING_TAGS=$(echo "$TAGS" | jq -r '.results[].name' | grep -E "$TAG_REGEX" | sort -Vr)

            for TAG in $MATCHING_TAGS; do
              if [[ -z "$LATEST_TAG" ]]; then
                export LATEST_TAG=$TAG
                break
              fi
            done

            [[ -n "$LATEST_TAG" ]] && break

            NEXT_PAGE=$(echo "$TAGS" | jq -r '.next')
            [[ "$NEXT_PAGE" == "null" ]] && break

            PAGE=$((PAGE + 1))
          done

          if [[ -z "$LATEST_TAG" ]]; then
            echo "No matching tags found." >&2
            exit 1
          fi

          echo "Found latest tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> "$GITHUB_OUTPUT"

      - name: Update secrets
        run: |
          if [ "${{ steps.fetch.outputs.LATEST_TAG }}" != "${{ vars.GRAFANA_IMAGE_TAG }}" ]; then
            echo "Current tag: ${{ vars.GRAFANA_IMAGE_TAG }}"
            echo "Latest tag: $LATEST_TAG"
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_DEFAULT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"GRAFANA_IMAGE_TAG\",\"value\":\"${{ steps.fetch.outputs.LATEST_TAG }}\"}" \
              https://api.github.com/repos/v6Org01/grafana/actions/variables/GRAFANA_IMAGE_TAG
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_DEFAULT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"event_type\":\"trigger-wf-pushImage2Registry\"}" \
              https://api.github.com/repos/v6Org01/grafana/dispatches
          else
            echo "No new version found."
          fi
